spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wei19970707
    url: jdbc:mysql://119.29.20.227/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
  port: 80
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: G:/var/log
wechat:
   mpAppId: wxa44dc0ce28b5d078
   mpAppSecret: 4ddeda9b9cda16e70cf47f6660200f36
#   openAppId: wx6ad144e54af67d87
#   openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
#   mchId: 1483469312
#   mchKey: 06C56A89949D617xxxxxxxxxxx
#   keyPath: /var/weixin_cert/h5.p12
#   notifyUrl: http://sell.natapp4.cc/sell/pay/notify
#   templateId:
#   orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://weiqiubin.natapp1.cc
  wechatOpenAuthorize: http://weiqiubin.natapp1.cc
  sell: http://weiqiubin.natapp1.cc
