spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: wei19970707
    url: jdbc:mysql://119.29.20.227/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: G:/var/log